### ISSUE TITLE
Feature de Traduction

### ISSUE THREAD

**Issue by Tri125** [Nutritia/nutritia#109]
### Traduction en cours:
- [x] MainWindow
- [x] TabValeurNutri
- [x] StackPlatAliment **Vide**
- [x] SearchBox
- [x] FenetreVotes **problème**, #96 #108
- [x] FenetreVote
- [x] FenetreSuiviRestrictions
- [x] FenetreSauvegarderMenu
- [x] FenetreRecuDon
- [x] FenetreParametres
  - [x] MenuConnexion
  - [x] MenuGeneral ~~**problème**, #99~~
- [x] FenetreOuvrirMenu
- [x] FenetreModificationProfil **problème**, #101 
- [x] FenetreMenuPrincipalConnecte **problème**, #102 
- [x] FenetreMenuPrincipal **problème**, #102
- [x] FenetreMenuAdministrateur
- [x] FenetreListeEpicerie **voir code fenêtre** peut avoir problème avec changement BD anglais.
- [x] FenetreIngredients **problème**, Rajout de labels par dessus d'autres. peut avoir problème avec changement BD anglais.
- [x] FenetreInfoMembre
- [x] FenetreGestionRepertoire **TODO** après merge de Richard
- [x] FenetreGestionAdmin
- [x] FenetreGenerateurMenus **manque**, sauf les string de séparateur de plats "Déjeuner", "Breuvage", etc.
- [x] FenetreCreationProfil
- [x] FenetreConnexion
- [x] FenetreCalculatriceNutritionnelle **problème**, pas de changement dynamique. Voir code-behind.
- [x] FenetreBannissement
- [x] FenetreAPropos
  - [x] Don
  - [x] Information
- [x] FenetreAjoutPlatMembre **Vide**
- [x] FenetreAjoutPlatAdmin **Vide**
- [x] FenetreAide

**TODO**

Facture. Code QR juste en français :(

**Nb: Possible d'avoir skippé la traduction des Headers de plusieurs datagrid de l'application et certain titre de fenêtres.**
